OPENAI_API_KEY = "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"


GEMINI_API_KEY ="AIzaSyByz2fCoMLCiLP1T8e2UFlnNG96s7RlzSE"